name = "anq-platform"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# 生产环境配置
[env.production]
kv_namespaces = [
  { binding = "SAFETY_CONTENT", id = "baa98240dd524851bce5ab53079c3994" },
  { binding = "ANALYTICS_STORE", id = "c61c562173de42d4bb5aa614faff2cba" },
  { binding = "CACHE_STORE", id = "e40819a68b5740bf8741ea93991f6ed9" },
  { binding = "RATE_LIMIT_STORE", id = "29ad0bd8fe264511969306ef1d3ac0cb" }
]

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://anq-platform.pages.dev"
LOG_LEVEL = "info"
CACHE_TTL = "3600"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# 预览环境配置
[env.preview]
kv_namespaces = [
  { binding = "SAFETY_CONTENT", preview_id = "baa98240dd524851bce5ab53079c3994" },
  { binding = "ANALYTICS_STORE", preview_id = "c61c562173de42d4bb5aa614faff2cba" },
  { binding = "CACHE_STORE", preview_id = "e40819a68b5740bf8741ea93991f6ed9" },
  { binding = "RATE_LIMIT_STORE", preview_id = "29ad0bd8fe264511969306ef1d3ac0cb" }
]

[env.preview.vars]
ENVIRONMENT = "preview"
API_BASE_URL = "https://preview.anq-platform.pages.dev"
LOG_LEVEL = "debug"
CACHE_TTL = "300"
RATE_LIMIT_REQUESTS = "200"
RATE_LIMIT_WINDOW = "60"
