name = "anq-platform"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# 生产环境配置
[env.production]
kv_namespaces = [
  { binding = "CONTENT_STORE", id = "your_content_kv_id" },
  { binding = "ANALYTICS_STORE", id = "your_analytics_kv_id" },
  { binding = "CACHE_STORE", id = "your_cache_kv_id" },
  { binding = "RATE_LIMIT_STORE", id = "your_rate_limit_kv_id" }
]

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://anq-platform.pages.dev"
LOG_LEVEL = "info"
CACHE_TTL = "3600"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60"

# 预览环境配置
[env.preview]
kv_namespaces = [
  { binding = "CONTENT_STORE", preview_id = "your_content_kv_preview_id" },
  { binding = "ANALYTICS_STORE", preview_id = "your_analytics_kv_preview_id" },
  { binding = "CACHE_STORE", preview_id = "your_cache_kv_preview_id" },
  { binding = "RATE_LIMIT_STORE", preview_id = "your_rate_limit_kv_preview_id" }
]

[env.preview.vars]
ENVIRONMENT = "preview"
API_BASE_URL = "https://preview.anq-platform.pages.dev"
LOG_LEVEL = "debug"
CACHE_TTL = "300"
RATE_LIMIT_REQUESTS = "200"
RATE_LIMIT_WINDOW = "60"

# 开发环境配置
[env.development]
kv_namespaces = [
  { binding = "CONTENT_STORE", preview_id = "your_content_kv_dev_id" },
  { binding = "ANALYTICS_STORE", preview_id = "your_analytics_kv_dev_id" },
  { binding = "CACHE_STORE", preview_id = "your_cache_kv_dev_id" },
  { binding = "RATE_LIMIT_STORE", preview_id = "your_rate_limit_kv_dev_id" }
]

[env.development.vars]
ENVIRONMENT = "development"
API_BASE_URL = "http://localhost:8788"
LOG_LEVEL = "debug"
CACHE_TTL = "60"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "60"
